name: Build And Test on All OSs
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 11, 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest && go env

      - name: Build and execute unit tests (Windows)
        run: task test "SEP=;"
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Build and execute unit tests (non-Windows)
        run: task test
        if: ${{ matrix.os != 'windows-latest' }}

      - name: Build and execute integration tests (Windows)
        run: task integration-test "SEP=;"
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Build and execute integration tests (non-Windows)
        run: task integration-test
        if: ${{ matrix.os != 'windows-latest' }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JUnit Tests
          path: out/test-reports/(test|integrationTest)/TEST-*.xml
          reporter: java-junit
