name: Build And Test on All OSs
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [11, 17]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Build and execute unit tests
        run: task test

      - name: Build and execute integration tests
        run: task integration-test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JUnit Tests
          path: out/test-reports/(test|integrationTest)/TEST-*.xml
          reporter: java-junit
