name: Build And Test on All OSs
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 11, 17, 21 ]
        include:
            - os: ubuntu-latest
              oskind: linux
            - os: macos-latest
              oskind: macos-arm64
            - os: windows-latest
              oskind: windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Download jb
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'renatoathaydes/jb'
          version: 'tags/0.8.0'
          file: 'jb-0.8.0-${{ matrix.oskind }}.tar.gz'
          target: jb.tar.gz

      - name: Install jb
        run: |
              mkdir jb
              tar xzf jb.tar.gz -C jb
        shell: bash

      - name: Build and test jbuild-classfile-parser
        run: jb/bin/jb -d -p jbuild-classfile-parser/test test
        shell: bash

      - name: Build and test JBuild main artifact
        run: jb/bin/jb -d -p src/test test
        shell: bash

      - name: Build and execute integration tests
        run: jb/bin/jb -l debug -d -p src/intTest test
        shell: bash

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JUnit Tests
          path: build/test-reports/(test|intTest)/TEST-*.xml
          reporter: java-junit
